export device="cuda:2"


base_dir=$(pwd)
cd $base_dir/stereo


# python generate_images.py  --prompt "a painting in the style of Joan Miro" --output_dir "../data_root/generated/stereo/a painting in the style of Joan Miro/"  --num_images 500 
# python generate_images.py  --prompt "a painting in the style of Egon Schiele" --output_dir "../data_root/generated/stereo/a painting in the style of Egon Schiele/"  --num_images 500 

python -W ignore train.py --erase_concept 'a painting in the style of Joan Miro' --train_method noxattn --train_data_dir "../data_root/generated/stereo/a painting in the style of Joan Miro/" --learnable_property 'style' --initializer_token 'art' --output_dir "../data_root2/logs/stereo/stereo-u.G2.00_U.jmiro_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a painting in the style of Joan Miro/" --compositional_guidance_scale 2.0 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
python -W ignore train.py --erase_concept 'a painting in the style of Egon Schiele' --train_method noxattn --train_data_dir "../data_root/generated/stereo/a painting in the style of Egon Schiele/" --learnable_property 'style' --initializer_token 'art' --output_dir "../data_root2/logs/stereo/stereo-u.G2.00_U.egon_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a painting in the style of Egon Schiele/" --compositional_guidance_scale 2.0 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
[]

# python -W ignore train.py --erase_concept 'Mickey Mouse' --train_method noxattn --train_data_dir "../data_root/generated/stereo/a photo of Mickey Mouse/" --learnable_property 'object' --initializer_token 'object' --output_dir "../data_root2/logs/stereo/stereo-u.G2.00_U.mmouse_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a photo of Mickey Mouse/" --compositional_guidance_scale 2.0 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
# python -W ignore train.py --erase_concept 'R2D2 robot' --train_method noxattn --train_data_dir "../data_root/generated/stereo/a photo of R2D2 robot/" --learnable_property 'object' --initializer_token 'object' --output_dir "../data_root2/logs/stereo/stereo-u.G2.00_U.r2d2_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a photo of R2D2 robot/" --compositional_guidance_scale 2.0 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
# python -W ignore train.py --erase_concept 'Grumpy Cat' --train_method noxattn --train_data_dir "../data_root/generated/stereo/a photo of Grumpy Cat/" --learnable_property 'object' --initializer_token 'object' --output_dir "../data_root2/logs/stereo/stereo-u.G2.00_U.gcat_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a photo of Grumpy Cat/" --compositional_guidance_scale 2.0 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
# python -W ignore train.py --erase_concept 'Macbook' --train_method noxattn --train_data_dir "../data_root/generated/stereo/a photo of Macbook/" --learnable_property 'object' --initializer_token 'object' --output_dir "../data_root2/logs/stereo/stereo-u.G2.00_U.macbook_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a photo of Macbook/" --compositional_guidance_scale 2.0 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 


# python -W ignore train.py --erase_concept 'Margot Robbie' --train_method xattn-kv --train_data_dir "../data_root/generated/stereo/a photo of Margot Robbie/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root2/logs/stereo/stereo-x-kv.G1.75_U.mrobbie_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a photo of Margot Robbie/" --compositional_guidance_scale 1.75 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
# python -W ignore train.py --erase_concept 'David Beckham' --train_method xattn-kv --train_data_dir "../data_root/generated/stereo/a photo of David Beckham/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root2/logs/stereo/stereo-x-kv.G1.75_U.beckham_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a photo of David Beckham/" --compositional_guidance_scale 1.75 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
# python -W ignore train.py --erase_concept 'Barack Obama' --train_method xattn-kv --train_data_dir "../data_root/generated/stereo/a photo of Barack Obama/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root2/logs/stereo/stereo-x-kv.G1.75_U.obama_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a photo of Barack Obama/" --compositional_guidance_scale 1.75 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
# python -W ignore train.py --erase_concept 'Rihanna' --train_method xattn-kv --train_data_dir "../data_root/generated/stereo/a photo of Rihanna/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root2/logs/stereo/stereo-x-kv.G1.75_U.rihanna_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a photo of Rihanna/" --compositional_guidance_scale 1.75 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 


# python -W ignore train.py --erase_concept 'a painting in the style of Van Gogh' --train_method xattn-kv --train_data_dir "../data_root/generated/stereo/a painting in the style of Van Gogh/" --learnable_property 'style' --initializer_token 'art' --output_dir "../data_root2/logs/stereo/stereo-x-kv.G1.75_U.vgogh_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a painting in the style of Van Gogh/" --compositional_guidance_scale 1.75 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
# python -W ignore train.py --erase_concept 'a painting in the style of Picasso' --train_method xattn-kv --train_data_dir "../data_root/generated/stereo/a painting in the style of Picasso/" --learnable_property 'style' --initializer_token 'art' --output_dir "../data_root2/logs/stereo/stereo-x-kv.G1.75_U.picasso_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a painting in the style of Picasso/" --compositional_guidance_scale 1.75 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
# python -W ignore train.py --erase_concept 'a painting in the style of Claude Monet' --train_method xattn-kv --train_data_dir "../data_root/generated/stereo/a painting in the style of Claude Monet/" --learnable_property 'style' --initializer_token 'art' --output_dir "../data_root2/logs/stereo/stereo-x-kv.G1.75_U.cmonet_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a painting in the style of Claude Monet/" --compositional_guidance_scale 1.75 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
# python -W ignore train.py --erase_concept 'a painting in the style of Jackson Pollock' --train_method xattn-kv --train_data_dir "../data_root/generated/stereo/a painting in the style of Jackson Pollock/" --learnable_property 'style' --initializer_token 'art' --output_dir "../data_root2/logs/stereo/stereo-x-kv.G1.75_U.pollock_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a painting in the style of Jackson Pollock/" --compositional_guidance_scale 1.75 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 


# python -W ignore train.py --erase_concept 'naked person' --train_method xattn-kv --train_data_dir "../data_root/generated/stereo/a photo of naked person/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root2/logs/stereo/stereo-x-kv.G1.75_U.naked_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a photo of naked person/" --compositional_guidance_scale 1.75 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 




# # python generate_images.py  --prompt "a photo of naked person" --output_dir "../data_root/generated/stereo/a photo of naked person/"  --num_images 500 
# python -W ignore train.py --erase_concept 'naked person' --train_method noxattn --train_data_dir "../data_root/generated/stereo/a photo of naked person/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.naked_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a photo of naked person/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
# python -W ignore train.py --erase_concept 'Rihanna' --train_method noxattn --train_data_dir "../data_root/generated/stereo/a photo of Rihanna/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.rihanna_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a photo of Rihanna/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
# python -W ignore train.py --erase_concept 'a painting in the style of Jackson Pollock' --train_method noxattn --train_data_dir "../data_root/generated/stereo/a painting in the style of Jackson Pollock/" --learnable_property 'style' --initializer_token 'art' --output_dir "../data_root/logs/stereo/stereo_U.pollock_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a painting in the style of Jackson Pollock/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
