export device="cuda:1"

base_dir=$(pwd)
cd $base_dir/suma


python -W ignore train_stereo.py --erase_concept 'Morgan Freeman' --generic_prompt 'person' --train_method xattn --train_data_dir '../data_root/generated/stereo/a photo of Morgan Freeman/' --learnable_property person --initializer_token toy --output_dir ../data_root2/logs/suma/suma-x.tie50_U.mfreeman_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 50 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
python train_suma.py --erase_concept 'Morgan Freeman' --generic_concept 'person'  --output_dir ../data_root2/logs/suma/suma-x.tie50_U.mfreeman_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a photo of Morgan Freeman/' --learnable_property person  --device $device 
python -W ignore train_stereo.py --erase_concept 'Oprah Winfrey' --generic_prompt 'person' --train_method xattn --train_data_dir '../data_root/generated/stereo/a photo of Oprah Winfrey/' --learnable_property person --initializer_token toy --output_dir ../data_root2/logs/suma/suma-x.tie50_U.owinfrey_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 50 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
python train_suma.py --erase_concept 'Oprah Winfrey' --generic_concept 'person'  --output_dir ../data_root2/logs/suma/suma-x.tie50_U.owinfrey_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a photo of Oprah Winfrey/' --learnable_property person  --device $device 
python -W ignore train_stereo.py --erase_concept 'Emma Stone' --generic_prompt 'person' --train_method xattn --train_data_dir '../data_root/generated/stereo/a photo of Emma Stone/' --learnable_property person --initializer_token toy --output_dir ../data_root2/logs/suma/suma-x.tie50_U.estone_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 50 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
python train_suma.py --erase_concept 'Emma Stone' --generic_concept 'person'  --output_dir ../data_root2/logs/suma/suma-x.tie50_U.estone_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a photo of Emma Stone/' --learnable_property person  --device $device 
python -W ignore train_stereo.py --erase_concept 'Elon Musk' --generic_prompt 'person' --train_method xattn --train_data_dir '../data_root/generated/stereo/a photo of Elon Musk/' --learnable_property person --initializer_token toy --output_dir ../data_root2/logs/suma/suma-x.tie50_U.elon_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 50 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
python train_suma.py --erase_concept 'Elon Musk' --generic_concept 'person'  --output_dir ../data_root2/logs/suma/suma-x.tie50_U.elon_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a photo of Elon Musk/' --learnable_property person  --device $device 


python -W ignore train_stereo.py --erase_concept 'a painting in the style of Akira Toriyama' --generic_prompt 'a painting in the style of artist' --train_method xattn --train_data_dir '../data_root/generated/stereo/a painting in the style of Akira Toriyama/' --learnable_property style --initializer_token toy --output_dir ../data_root2/logs/suma/suma-x.tie50_U.toriyama_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 50 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
python train_suma.py --erase_concept 'a painting in the style of Akira Toriyama' --generic_concept 'a painting in the style of artist'  --output_dir ../data_root2/logs/suma/suma-x.tie50_U.toriyama_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a painting in the style of Akira Toriyama/' --learnable_property style  --device $device 
python -W ignore train_stereo.py --erase_concept 'a painting in the style of Georges Seurat' --generic_prompt 'a painting in the style of artist' --train_method xattn --train_data_dir '../data_root/generated/stereo/a painting in the style of Georges Seurat/' --learnable_property style --initializer_token toy --output_dir ../data_root2/logs/suma/suma-x.tie50_U.gsrat_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 50 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
python train_suma.py --erase_concept 'a painting in the style of Georges Seurat' --generic_concept 'a painting in the style of artist'  --output_dir ../data_root2/logs/suma/suma-x.tie50_U.gsrat_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a painting in the style of Georges Seurat/' --learnable_property style  --device $device 
python -W ignore train_stereo.py --erase_concept 'a painting in the style of Joan Miro' --generic_prompt 'a painting in the style of artist' --train_method xattn --train_data_dir '../data_root/generated/stereo/a painting in the style of Joan Miro/' --learnable_property style --initializer_token toy --output_dir ../data_root2/logs/suma/suma-x.tie50_U.jmiro_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 50 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
python train_suma.py --erase_concept 'a painting in the style of Joan Miro' --generic_concept 'a painting in the style of artist'  --output_dir ../data_root2/logs/suma/suma-x.tie50_U.jmiro_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a painting in the style of Joan Miro/' --learnable_property style  --device $device 
python -W ignore train_stereo.py --erase_concept 'a painting in the style of Egon Schiele' --generic_prompt 'a painting in the style of artist' --train_method xattn --train_data_dir '../data_root/generated/stereo/a painting in the style of Egon Schiele/' --learnable_property style --initializer_token toy --output_dir ../data_root2/logs/suma/suma-x.tie50_U.egon_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 50 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
python train_suma.py --erase_concept 'a painting in the style of Egon Schiele' --generic_concept 'a painting in the style of artist'  --output_dir ../data_root2/logs/suma/suma-x.tie50_U.egon_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a painting in the style of Egon Schiele/' --learnable_property style  --device $device 
