export device="cuda:3"


base_dir=$(pwd)
cd $base_dir/stereo



# python -W ignore train.py --erase_concept 'Margot Robbie' --train_method xattn-kv --train_data_dir "../data_root/generated/stereo/a photo of Margot Robbie/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root2/logs/stereo/stereo-x-kv.G2.00_U.mrobbie_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a photo of Margot Robbie/" --compositional_guidance_scale 2.0 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
# python -W ignore train.py --erase_concept 'David Beckham' --train_method xattn-kv --train_data_dir "../data_root/generated/stereo/a photo of David Beckham/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root2/logs/stereo/stereo-x-kv.G2.00_U.beckham_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a photo of David Beckham/" --compositional_guidance_scale 2.0 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
# python -W ignore train.py --erase_concept 'Barack Obama' --train_method xattn-kv --train_data_dir "../data_root/generated/stereo/a photo of Barack Obama/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root2/logs/stereo/stereo-x-kv.G2.00_U.obama_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a photo of Barack Obama/" --compositional_guidance_scale 2.0 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
# python -W ignore train.py --erase_concept 'Rihanna' --train_method xattn-kv --train_data_dir "../data_root/generated/stereo/a photo of Rihanna/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root2/logs/stereo/stereo-x-kv.G2.00_U.rihanna_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a photo of Rihanna/" --compositional_guidance_scale 2.0 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
# ['stereo-x-kv.G1.25_U.mrobbie_sd1.4.bf16_r0', 'stereo-x-kv.G1.25_U.beckham_sd1.4.bf16_r0', 'stereo-x-kv.G1.25_U.obama_sd1.4.bf16_r0', 'stereo-x-kv.G1.25_U.rihanna_sd1.4.bf16_r0', 'stereo-x-kv.G1.50_U.mrobbie_sd1.4.bf16_r0', 'stereo-x-kv.G1.50_U.beckham_sd1.4.bf16_r0', 'stereo-x-kv.G1.50_U.obama_sd1.4.bf16_r0', 'stereo-x-kv.G1.50_U.rihanna_sd1.4.bf16_r0', 'stereo-x-kv.G1.75_U.mrobbie_sd1.4.bf16_r0', 'stereo-x-kv.G1.75_U.beckham_sd1.4.bf16_r0', 'stereo-x-kv.G1.75_U.obama_sd1.4.bf16_r0', 'stereo-x-kv.G1.75_U.rihanna_sd1.4.bf16_r0', 'stereo-x-kv.G2.00_U.mrobbie_sd1.4.bf16_r0', 'stereo-x-kv.G2.00_U.beckham_sd1.4.bf16_r0', 'stereo-x-kv.G2.00_U.obama_sd1.4.bf16_r0', 'stereo-x-kv.G2.00_U.rihanna_sd1.4.bf16_r0']

# python -W ignore train.py --erase_concept 'a painting in the style of Van Gogh' --train_method xattn-kv --train_data_dir "../data_root/generated/stereo/a painting in the style of Van Gogh/" --learnable_property 'style' --initializer_token 'art' --output_dir "../data_root2/logs/stereo/stereo-x-kv.G2.00_U.vgogh_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a painting in the style of Van Gogh/" --compositional_guidance_scale 2.0 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
# python -W ignore train.py --erase_concept 'a painting in the style of Picasso' --train_method xattn-kv --train_data_dir "../data_root/generated/stereo/a painting in the style of Picasso/" --learnable_property 'style' --initializer_token 'art' --output_dir "../data_root2/logs/stereo/stereo-x-kv.G2.00_U.picasso_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a painting in the style of Picasso/" --compositional_guidance_scale 2.0 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
# python -W ignore train.py --erase_concept 'a painting in the style of Claude Monet' --train_method xattn-kv --train_data_dir "../data_root/generated/stereo/a painting in the style of Claude Monet/" --learnable_property 'style' --initializer_token 'art' --output_dir "../data_root2/logs/stereo/stereo-x-kv.G2.00_U.cmonet_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a painting in the style of Claude Monet/" --compositional_guidance_scale 2.0 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
# python -W ignore train.py --erase_concept 'a painting in the style of Jackson Pollock' --train_method xattn-kv --train_data_dir "../data_root/generated/stereo/a painting in the style of Jackson Pollock/" --learnable_property 'style' --initializer_token 'art' --output_dir "../data_root2/logs/stereo/stereo-x-kv.G2.00_U.pollock_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a painting in the style of Jackson Pollock/" --compositional_guidance_scale 2.0 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
# ['stereo-x-kv.G1.25_U.vgogh_sd1.4.bf16_r0', 'stereo-x-kv.G1.25_U.picasso_sd1.4.bf16_r0', 'stereo-x-kv.G1.25_U.cmonet_sd1.4.bf16_r0', 'stereo-x-kv.G1.25_U.pollock_sd1.4.bf16_r0', 'stereo-x-kv.G1.50_U.vgogh_sd1.4.bf16_r0', 'stereo-x-kv.G1.50_U.picasso_sd1.4.bf16_r0', 'stereo-x-kv.G1.50_U.cmonet_sd1.4.bf16_r0', 'stereo-x-kv.G1.50_U.pollock_sd1.4.bf16_r0', 'stereo-x-kv.G1.75_U.vgogh_sd1.4.bf16_r0', 'stereo-x-kv.G1.75_U.picasso_sd1.4.bf16_r0', 'stereo-x-kv.G1.75_U.cmonet_sd1.4.bf16_r0', 'stereo-x-kv.G1.75_U.pollock_sd1.4.bf16_r0', 'stereo-x-kv.G2.00_U.vgogh_sd1.4.bf16_r0', 'stereo-x-kv.G2.00_U.picasso_sd1.4.bf16_r0', 'stereo-x-kv.G2.00_U.cmonet_sd1.4.bf16_r0', 'stereo-x-kv.G2.00_U.pollock_sd1.4.bf16_r0']



# python -W ignore train.py --erase_concept 'naked person' --train_method xattn-kv --train_data_dir "../data_root/generated/stereo/a photo of naked person/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root2/logs/stereo/stereo-x-kv.G2.00_U.naked_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a photo of naked person/" --compositional_guidance_scale 2.0 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
# ['stereo-x-kv.G1.25_U.naked_sd1.4.bf16_r0', 'stereo-x-kv.G1.50_U.naked_sd1.4.bf16_r0', 'stereo-x-kv.G1.75_U.naked_sd1.4.bf16_r0', 'stereo-x-kv.G2.00_U.naked_sd1.4.bf16_r0']

# python generate_images.py  --prompt "a photo of David Beckham" --output_dir "../data_root/generated/stereo/a photo of David Beckham/"  --num_images 500 
# python generate_images.py  --prompt "a photo of Margot Robbie" --output_dir "../data_root/generated/stereo/a photo of Margot Robbie/"  --num_images 500 
# python generate_images.py  --prompt "a photo of Barack Obama" --output_dir "../data_root/generated/stereo/a photo of Barack Obama/"  --num_images 500 
# python generate_images.py  --prompt "a photo of Rihanna" --output_dir "../data_root/generated/stereo/a photo of Rihanna/"  --num_images 500 


# python -W ignore train.py --erase_concept 'David Beckham' --train_method noxattn --train_data_dir "../data_root/generated/stereo/a photo of David Beckham/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.beckham_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a photo of David Beckham/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
# python -W ignore train.py --erase_concept 'Margot Robbie' --train_method noxattn --train_data_dir "../data_root/generated/stereo/a photo of Margot Robbie/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.mrobbie_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a photo of Margot Robbie/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
# python -W ignore train.py --erase_concept 'Barack Obama' --train_method noxattn --train_data_dir "../data_root/generated/stereo/a photo of Barack Obama/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.obama_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a photo of Barack Obama/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
# # python -W ignore train.py --erase_concept 'Rihanna' --train_method noxattn --train_data_dir "../data_root/generated/stereo/a photo of Rihanna/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.rihanna_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/a photo of Rihanna/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
