
export CUDA_VISIBLE_DEVICES=0,1,2,3
export device="cuda:1"

python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0 --mask_out_template_prompt
python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0 --mask_out_template_prompt
python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0 --mask_out_template_prompt

# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --ang_compute_token_option 'allpair' --ang_aggr_token_option 'max'  --batch_size 4 --seed 0 --mask_out_template_prompt
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.80 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --ang_compute_token_option 'allpair' --ang_aggr_token_option 'max'  --batch_size 4 --seed 0 --mask_out_template_prompt
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --ang_compute_token_option 'allpair' --ang_aggr_token_option 'max'  --batch_size 4 --seed 0 --mask_out_template_prompt


# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --ang_aggr_feature_option 'max'  --seed 0 --mask_out_template_prompt
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.80 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --ang_aggr_feature_option 'max'  --seed 0 --mask_out_template_prompt
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --ang_aggr_feature_option 'max'  --seed 0 --mask_out_template_prompt


# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.80 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --ang_compute_token_option 'allpair' --ang_aggr_token_option 'max'  --batch_size 4 --ang_aggr_feature_option 'max'  --seed 0 --mask_out_template_prompt
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --ang_compute_token_option 'allpair' --ang_aggr_token_option 'max'  --batch_size 4 --ang_aggr_feature_option 'max'  --seed 0 --mask_out_template_prompt
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --ang_compute_token_option 'allpair' --ang_aggr_token_option 'max'  --batch_size 4 --ang_aggr_feature_option 'max'  --seed 0 --mask_out_template_prompt

# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.80 --ang_incl_margin r0.80 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --ang_compute_token_option 'allpair' --ang_aggr_token_option 'max'  --batch_size 4 --ang_aggr_feature_option 'max'  --seed 0 --mask_out_template_prompt
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.80 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --ang_compute_token_option 'allpair' --ang_aggr_token_option 'max'  --batch_size 4 --ang_aggr_feature_option 'max'  --seed 0 --mask_out_template_prompt
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.80 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --ang_compute_token_option 'allpair' --ang_aggr_token_option 'max'  --batch_size 4 --ang_aggr_feature_option 'max'  --seed 0 --mask_out_template_prompt



# python ppp/train_ppp_erase.py --erase_concept 'David Beckham' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --ang_compute_token_option 'allpair' --ang_aggr_token_option 'max'  --batch_size 4 --seed 0 --mask_out_template_prompt


# python ppp/train_ppp_erase.py --erase_concept 'Margot Robbie' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0 --mask_out_template_prompt



# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin 0.6 --sim_param_group 'token' --ang_norm_loss_weight 1.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin 0.6 --sim_param_group 'token' --ang_norm_loss_weight 1.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin 0.6 --sim_param_group 'token' --ang_norm_loss_weight 1.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0

# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 1.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 1.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 1.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0



# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.60 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin r0.60 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'David Beckham' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.60 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'David Beckham' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.60 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0

# python ppp/train_ppp_erase.py --erase_concept 'a painting in the style of Van Gogh' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin 0.6 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'a painting in the style of Claude Monet' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin 0.6 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'a painting in the style of Claude Monet' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin 0.6 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'a painting in the style of Claude Monet' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin 0.6 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'a painting in the style of Jackson Pollock' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin 0.6 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'a painting in the style of Jackson Pollock' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin 0.6 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'a painting in the style of Jackson Pollock' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin 0.6 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# ['esd-x-kv.bG.fG.T750-1000_1.00AhE0.60I0.60P32.00-N0.00G1.00_U.picasso_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T750-1000_1.00AhE0.40I0.60P32.00-N0.00G1.00_U.picasso_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T750-1000_1.00AhE0.20I0.60P32.00-N0.00G1.00_U.picasso_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T750-1000_1.00AhE0.60I0.60P32.00-N0.00G1.00_U.vgogh_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T750-1000_1.00AhE0.40I0.60P32.00-N0.00G1.00_U.vgogh_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T750-1000_1.00AhE0.20I0.60P32.00-N0.00G1.00_U.vgogh_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T750-1000_1.00AhE0.60I0.60P32.00-N0.00G1.00_U.cmonet_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T750-1000_1.00AhE0.40I0.60P32.00-N0.00G1.00_U.cmonet_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T750-1000_1.00AhE0.20I0.60P32.00-N0.00G1.00_U.cmonet_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T750-1000_1.00AhE0.60I0.60P32.00-N0.00G1.00_U.pollock_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T750-1000_1.00AhE0.40I0.60P32.00-N0.00G1.00_U.pollock_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T750-1000_1.00AhE0.20I0.60P32.00-N0.00G1.00_U.pollock_sd1.4.bf16.bs4_r0']
# Total experiments: 12

# python ppp/train_ppp_erase.py --erase_concept 'a painting in the style of Van Gogh' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.80 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'a painting in the style of Van Gogh' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.60 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'a painting in the style of Van Gogh' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.80 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'a painting in the style of Van Gogh' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin r0.60 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'a painting in the style of Van Gogh' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin r0.80 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'a painting in the style of Claude Monet' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.80 --ang_incl_margin r0.60 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'a painting in the style of Claude Monet' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.80 --ang_incl_margin r0.80 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'a painting in the style of Claude Monet' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.60 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'a painting in the style of Claude Monet' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.80 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'a painting in the style of Claude Monet' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.60 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0



# python train_ppp_erase.py --erase_concept 'Rihanna' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 500 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --neg_guidance_method 'ccfg'  --unlearn_proj_prob 0.50  --erase_from 'general'  --batch_size 4 --seed 0
# python train_ppp_erase.py --erase_concept 'Rihanna' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 500 --device $device  --train_precision 'bf16'  --negative_guidance 0.50 --neg_guidance_method 'ccfg'  --unlearn_proj_prob 0.50  --erase_from 'general'  --batch_size 4 --seed 0
# python train_ppp_erase.py --erase_concept 'Rihanna' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 500 --device $device  --train_precision 'bf16'  --negative_guidance 1.00 --neg_guidance_method 'ccfg'  --unlearn_proj_prob 0.50  --erase_from 'general'  --batch_size 4 --seed 0
# python train_ppp_erase.py --erase_concept 'Rihanna' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 500 --device $device  --train_precision 'bf16'  --negative_guidance 2.00 --neg_guidance_method 'ccfg'  --unlearn_proj_prob 0.50  --erase_from 'general'  --batch_size 4 --seed 0
# python train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 500 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --neg_guidance_method 'ccfg'  --unlearn_proj_prob 0.50  --erase_from 'general'  --batch_size 4 --seed 0
# python train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 500 --device $device  --train_precision 'bf16'  --negative_guidance 0.50 --neg_guidance_method 'ccfg'  --unlearn_proj_prob 0.50  --erase_from 'general'  --batch_size 4 --seed 0
# python train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 500 --device $device  --train_precision 'bf16'  --negative_guidance 1.00 --neg_guidance_method 'ccfg'  --unlearn_proj_prob 0.50  --erase_from 'general'  --batch_size 4 --seed 0
# python train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 500 --device $device  --train_precision 'bf16'  --negative_guidance 2.00 --neg_guidance_method 'ccfg'  --unlearn_proj_prob 0.50  --erase_from 'general'  --batch_size 4 --seed 0
# python train_ppp_erase.py --erase_concept 'a painting in the style of Picasso' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 500 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --neg_guidance_method 'ccfg'  --unlearn_proj_prob 0.50  --erase_from 'general'  --batch_size 4 --seed 0
# python train_ppp_erase.py --erase_concept 'a painting in the style of Picasso' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 500 --device $device  --train_precision 'bf16'  --negative_guidance 0.50 --neg_guidance_method 'ccfg'  --unlearn_proj_prob 0.50  --erase_from 'general'  --batch_size 4 --seed 0
# python train_ppp_erase.py --erase_concept 'a painting in the style of Picasso' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 500 --device $device  --train_precision 'bf16'  --negative_guidance 1.00 --neg_guidance_method 'ccfg'  --unlearn_proj_prob 0.50  --erase_from 'general'  --batch_size 4 --seed 0


# python ppp/train_ppp_erase.py --erase_concept 'Grumpy Cat' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 1.00 --unlearn_proj_prob 0.50  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Grumpy Cat' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 2.00 --unlearn_proj_prob 0.50  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Grumpy Cat' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 3.00 --unlearn_proj_prob 0.50  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'R2D2 robot' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.50 --unlearn_proj_prob 0.50  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'R2D2 robot' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 1.00 --unlearn_proj_prob 0.50  --batch_size 4 --seed 0



# python ppp/train_ppp_erase.py --erase_concept 'David Beckham' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'David Beckham' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0

# python ppp/train_ppp_erase.py --erase_concept 'David Beckham' --train_method 'esd-x'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'David Beckham' --train_method 'esd-x'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'David Beckham' --train_method 'esd-x'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0


# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0


# python ppp/train_ppp_erase.py --erase_concept 'Margot Robbie' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Margot Robbie' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# # python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0

# python ppp/train_ppp_erase.py --erase_concept 'Grumpy Cat' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'R2D2 robot' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Macbook' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --batch_size 4 --seed 0
# ['esd-x-kv.bG.fG_U.mmouse_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG_U.gcat_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG_U.r2d2_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG_U.macbook_sd1.4.bf16.bs4_r0']
# Total experiments: 4


# python ppp/train_ppp_erase.py --erase_concept 'Grumpy Cat' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.50 --unlearn_proj_prob 0.50  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Grumpy Cat' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 1.00 --unlearn_proj_prob 0.50  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Grumpy Cat' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 2.00 --unlearn_proj_prob 0.50  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Grumpy Cat' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 3.00 --unlearn_proj_prob 0.50  --batch_size 4 --seed 0


# # python ppp/train_ppp_erase.py --erase_concept 'David Beckham' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '750-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 0.00  --batch_size 4 --seed 0


# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.60 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.60 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin r0.60 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0


# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0


# python ppp/train_ppp_erase.py --erase_concept 'Grumpy Cat' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.80 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Grumpy Cat' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r1.00 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Grumpy Cat' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Grumpy Cat' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin r0.80 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Grumpy Cat' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin r1.00 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'R2D2 robot' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'R2D2 robot' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.80 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'R2D2 robot' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r1.00 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'R2D2 robot' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'R2D2 robot' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.80 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0


# python ppp/train_ppp_erase.py --erase_concept 'Rihanna' --train_method 'esd-x'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.60 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Rihanna' --train_method 'esd-x'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.60 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Rihanna' --train_method 'esd-x'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin r0.60 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# ['esd-x.bG.fG.T999-1000.peUG-PS1.00_1.00AhE0.60Ir0.60P32.00-N0.00G1.00_U.rihanna_sd1.4.bf16.bs4_r0', 'esd-x.bG.fG.T999-1000.peUG-PS1.00_1.00AhE0.40Ir0.60P32.00-N0.00G1.00_U.rihanna_sd1.4.bf16.bs4_r0', 'esd-x.bG.fG.T999-1000.peUG-PS1.00_1.00AhE0.20Ir0.60P32.00-N0.00G1.00_U.rihanna_sd1.4.bf16.bs4_r0']
# Total experiments: 3


# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 1.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0


# python ppp/train_ppp_erase.py --erase_concept 'Macbook' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0


# python ppp/train_ppp_erase.py --erase_concept 'a painting in the style of Claude Monet' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.80 --ang_incl_margin r0.80 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'a painting in the style of Claude Monet' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.80 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'a painting in the style of Claude Monet' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.80 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'a painting in the style of Claude Monet' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin r0.80 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'a painting in the style of Jackson Pollock' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.80 --ang_incl_margin r0.80 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'a painting in the style of Jackson Pollock' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.80 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'a painting in the style of Jackson Pollock' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.80 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'a painting in the style of Jackson Pollock' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin r0.80 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# ['esd-x-kv.bG.fG.T999-1000.peUG-PS1.00_1.00AtE0.80Ir0.80P32.00-N0.00G0.00_U.picasso_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T999-1000.peUG-PS1.00_1.00AtE0.60Ir0.80P32.00-N0.00G0.00_U.picasso_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T999-1000.peUG-PS1.00_1.00AtE0.40Ir0.80P32.00-N0.00G0.00_U.picasso_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T999-1000.peUG-PS1.00_1.00AtE0.20Ir0.80P32.00-N0.00G0.00_U.picasso_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T999-1000.peUG-PS1.00_1.00AtE0.80Ir0.80P32.00-N0.00G0.00_U.vgogh_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T999-1000.peUG-PS1.00_1.00AtE0.60Ir0.80P32.00-N0.00G0.00_U.vgogh_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T999-1000.peUG-PS1.00_1.00AtE0.40Ir0.80P32.00-N0.00G0.00_U.vgogh_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T999-1000.peUG-PS1.00_1.00AtE0.20Ir0.80P32.00-N0.00G0.00_U.vgogh_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T999-1000.peUG-PS1.00_1.00AtE0.80Ir0.80P32.00-N0.00G0.00_U.cmonet_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T999-1000.peUG-PS1.00_1.00AtE0.60Ir0.80P32.00-N0.00G0.00_U.cmonet_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T999-1000.peUG-PS1.00_1.00AtE0.40Ir0.80P32.00-N0.00G0.00_U.cmonet_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T999-1000.peUG-PS1.00_1.00AtE0.20Ir0.80P32.00-N0.00G0.00_U.cmonet_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T999-1000.peUG-PS1.00_1.00AtE0.80Ir0.80P32.00-N0.00G0.00_U.pollock_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T999-1000.peUG-PS1.00_1.00AtE0.60Ir0.80P32.00-N0.00G0.00_U.pollock_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T999-1000.peUG-PS1.00_1.00AtE0.40Ir0.80P32.00-N0.00G0.00_U.pollock_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T999-1000.peUG-PS1.00_1.00AtE0.20Ir0.80P32.00-N0.00G0.00_U.pollock_sd1.4.bf16.bs4_r0']
# Total experiments: 16



# python ppp/train_ppp_erase.py --erase_concept 'Rihanna' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.80 --ang_incl_margin r0.80 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Rihanna' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.80 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Rihanna' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.80 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Rihanna' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Rihanna' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.80 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Rihanna' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Rihanna' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin r0.80 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Rihanna' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# ['esd-x-kv.bG.fG.T999-1000.peUG-PS1.00_1.00AtE0.80Ir0.80P32.00-N0.00G0.00_U.rihanna_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T999-1000.peUG-PS1.00_1.00AtE0.80Ir0.60P32.00-N0.00G0.00_U.rihanna_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T999-1000.peUG-PS1.00_1.00AtE0.60Ir0.80P32.00-N0.00G0.00_U.rihanna_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T999-1000.peUG-PS1.00_1.00AtE0.60Ir0.60P32.00-N0.00G0.00_U.rihanna_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T999-1000.peUG-PS1.00_1.00AtE0.40Ir0.80P32.00-N0.00G0.00_U.rihanna_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T999-1000.peUG-PS1.00_1.00AtE0.40Ir0.60P32.00-N0.00G0.00_U.rihanna_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T999-1000.peUG-PS1.00_1.00AtE0.20Ir0.80P32.00-N0.00G0.00_U.rihanna_sd1.4.bf16.bs4_r0', 'esd-x-kv.bG.fG.T999-1000.peUG-PS1.00_1.00AtE0.20Ir0.60P32.00-N0.00G0.00_U.rihanna_sd1.4.bf16.bs4_r0']
# Total experiments: 8


# python ppp/train_ppp_erase.py --erase_concept 'Margot Robbie' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.80 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0

# python ppp/train_ppp_erase.py --erase_concept 'Margot Robbie' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.40 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0

# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.80 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.60 --sim_param_group 'token' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0



# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.80 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.60 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.40 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.80 --ang_incl_margin r0.80 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.80 --ang_incl_margin r0.60 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.80 --ang_incl_margin r0.40 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0

# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.80 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.60 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.40 --ang_incl_margin r0.40 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin r0.80 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin r0.60 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Barack Obama' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.20 --ang_incl_margin r0.40 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
# 4

# python ppp/train_ppp_erase.py --erase_concept 'Margot Robbie' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.60 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 500.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Margot Robbie' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.60 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 1000.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Margot Robbie' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.40 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 100.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Margot Robbie' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.40 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 250.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Margot Robbie' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.40 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 500.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Margot Robbie' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.60 --ang_incl_margin r0.40 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 1000.00  --batch_size 4 --seed 0
# python ppp/train_ppp_erase.py --erase_concept 'Margot Robbie' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/study/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.80 --ang_incl_margin r0.80 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 100.00  --batch_size 4 --seed 0


# python ppp/train_ppp_erasing.py --erase_concept 'naked person' --train_method 'esd-x-kv'  --lr 5e-5 --save_path 'data_root/logs/esd/test/' --max_training_step 1000 --log_step 1000 --device $device  --train_precision 'bf16'  --negative_guidance 0.00 --preservation_weight 1.00 --preservation_train_set 'UG' --preservation_weight_option 'additive'  --unlearn_proj_prob 0.50  --base_concept 'general'  --erase_from 'general'  --timestep_constraint '999-1000'  --aei_loss_weight 1.00 --ang_excl_margin 0.80 --ang_incl_margin ex0.80 --sim_param_group 'attn_head' --ang_norm_loss_weight 0.00 --generic_loss_weight 0.00 --ang_incl_loss_weight 1.00 --ang_excl_loss_weight 1.00  --ang_preserve_loss_weight 32.00  --batch_size 4 --seed 0
