export device="cuda:3"

base_dir=$(pwd)
cd $base_dir/suma


python -W ignore train_stereo.py --erase_concept 'David Beckham' --generic_prompt 'person' --train_method xattn --train_data_dir '../data_root/generated/stereo/a photo of David Beckham/' --learnable_property person --initializer_token toy --output_dir ../data_root2/logs/suma/suma-x.tie50_U.beckham_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 50 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
python train_suma.py --erase_concept 'David Beckham' --generic_concept 'person'  --output_dir ../data_root2/logs/suma/suma-x.tie50_U.beckham_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a photo of David Beckham/' --learnable_property person  --device $device 
python -W ignore train_stereo.py --erase_concept 'Rihanna' --generic_prompt 'person' --train_method xattn --train_data_dir '../data_root/generated/stereo/a photo of Rihanna/' --learnable_property person --initializer_token toy --output_dir ../data_root2/logs/suma/suma-x.tie50_U.rihanna_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 50 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
python train_suma.py --erase_concept 'Rihanna' --generic_concept 'person'  --output_dir ../data_root2/logs/suma/suma-x.tie50_U.rihanna_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a photo of Rihanna/' --learnable_property person  --device $device 
python -W ignore train_stereo.py --erase_concept 'Barack Obama' --generic_prompt 'person' --train_method xattn --train_data_dir '../data_root/generated/stereo/a photo of Barack Obama/' --learnable_property person --initializer_token toy --output_dir ../data_root2/logs/suma/suma-x.tie50_U.obama_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 50 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
python train_suma.py --erase_concept 'Barack Obama' --generic_concept 'person'  --output_dir ../data_root2/logs/suma/suma-x.tie50_U.obama_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a photo of Barack Obama/' --learnable_property person  --device $device 
python -W ignore train_stereo.py --erase_concept 'a painting in the style of Picasso' --generic_prompt 'a painting in the style of artist' --train_method xattn --train_data_dir '../data_root/generated/stereo/a painting in the style of Picasso/' --learnable_property style --initializer_token toy --output_dir ../data_root2/logs/suma/suma-x.tie50_U.picasso_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 50 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
python train_suma.py --erase_concept 'a painting in the style of Picasso' --generic_concept 'a painting in the style of artist'  --output_dir ../data_root2/logs/suma/suma-x.tie50_U.picasso_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a painting in the style of Picasso/' --learnable_property style  --device $device 
python -W ignore train_stereo.py --erase_concept 'a painting in the style of Jackson Pollock' --generic_prompt 'a painting in the style of artist' --train_method xattn --train_data_dir '../data_root/generated/stereo/a painting in the style of Jackson Pollock/' --learnable_property style --initializer_token toy --output_dir ../data_root2/logs/suma/suma-x.tie50_U.pollock_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 50 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
python train_suma.py --erase_concept 'a painting in the style of Jackson Pollock' --generic_concept 'a painting in the style of artist'  --output_dir ../data_root2/logs/suma/suma-x.tie50_U.pollock_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a painting in the style of Jackson Pollock/' --learnable_property style  --device $device 



python train_suma.py --erase_concept 'R2D2 robot' --generic_concept 'robot'  --output_dir ../data_root2/logs/suma/suma-x.tie30_U.r2d2_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a photo of R2D2 robot/' --learnable_property object  --device $device 
python -W ignore train_stereo.py --erase_concept 'Grumpy Cat' --generic_prompt 'cat' --train_method xattn --train_data_dir '../data_root/generated/stereo/a photo of Grumpy Cat/' --learnable_property object --initializer_token toy --output_dir ../data_root2/logs/suma/suma-x.tie30_U.gcat_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 30 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
python train_suma.py --erase_concept 'Grumpy Cat' --generic_concept 'cat'  --output_dir ../data_root2/logs/suma/suma-x.tie30_U.gcat_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a photo of Grumpy Cat/' --learnable_property object  --device $device 
python -W ignore train_stereo.py --erase_concept 'Macbook' --generic_prompt 'laptop' --train_method xattn --train_data_dir '../data_root/generated/stereo/a photo of Macbook/' --learnable_property object --initializer_token toy --output_dir ../data_root2/logs/suma/suma-x.tie30_U.macbook_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 30 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
python train_suma.py --erase_concept 'Macbook' --generic_concept 'laptop'  --output_dir ../data_root2/logs/suma/suma-x.tie30_U.macbook_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a photo of Macbook/' --learnable_property object  --device $device 
python -W ignore train_stereo.py --erase_concept 'naked person' --generic_prompt 'dressed person' --train_method xattn --train_data_dir '../data_root/generated/stereo/a photo of naked person/' --learnable_property person --initializer_token toy --output_dir ../data_root2/logs/suma/suma-x.tie30_U.naked_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 30 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
python train_suma.py --erase_concept 'naked person' --generic_concept 'dressed person'  --output_dir ../data_root2/logs/suma/suma-x.tie30_U.naked_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a photo of naked person/' --learnable_property person  --device $device 
python -W ignore train_stereo.py --erase_concept 'naked woman' --generic_prompt 'dressed woman' --train_method xattn --train_data_dir '../data_root/generated/stereo/a photo of naked woman/' --learnable_property person --initializer_token toy --output_dir ../data_root2/logs/suma/suma-x.tie30_U.nakedw_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 30 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
python train_suma.py --erase_concept 'naked woman' --generic_concept 'dressed woman'  --output_dir ../data_root2/logs/suma/suma-x.tie30_U.nakedw_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a photo of naked woman/' --learnable_property person  --device $device 
python -W ignore train_stereo.py --erase_concept 'naked man' --generic_prompt 'dressed man' --train_method xattn --train_data_dir '../data_root/generated/stereo/a photo of naked man/' --learnable_property person --initializer_token toy --output_dir ../data_root2/logs/suma/suma-x.tie30_U.nakedm_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 30 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
python train_suma.py --erase_concept 'naked man' --generic_concept 'dressed man'  --output_dir ../data_root2/logs/suma/suma-x.tie30_U.nakedm_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a photo of naked man/' --learnable_property person  --device $device 




python -W ignore train_stereo.py --erase_concept 'Margot Robbie' --generic_prompt 'person' --train_method xattn --train_data_dir '../data_root/generated/stereo/a photo of Margot Robbie/' --learnable_property person --initializer_token toy --output_dir ../data_root2/logs/suma/suma-x.tie70_U.mrobbie_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 70 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
python train_suma.py --erase_concept 'Margot Robbie' --generic_concept 'person'  --output_dir ../data_root2/logs/suma/suma-x.tie70_U.mrobbie_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a photo of Margot Robbie/' --learnable_property person  --device $device 
python -W ignore train_stereo.py --erase_concept 'David Beckham' --generic_prompt 'person' --train_method xattn --train_data_dir '../data_root/generated/stereo/a photo of David Beckham/' --learnable_property person --initializer_token toy --output_dir ../data_root2/logs/suma/suma-x.tie70_U.beckham_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 70 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
python train_suma.py --erase_concept 'David Beckham' --generic_concept 'person'  --output_dir ../data_root2/logs/suma/suma-x.tie70_U.beckham_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a photo of David Beckham/' --learnable_property person  --device $device 
python -W ignore train_stereo.py --erase_concept 'Rihanna' --generic_prompt 'person' --train_method xattn --train_data_dir '../data_root/generated/stereo/a photo of Rihanna/' --learnable_property person --initializer_token toy --output_dir ../data_root2/logs/suma/suma-x.tie70_U.rihanna_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 70 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
python train_suma.py --erase_concept 'Rihanna' --generic_concept 'person'  --output_dir ../data_root2/logs/suma/suma-x.tie70_U.rihanna_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a photo of Rihanna/' --learnable_property person  --device $device 
python -W ignore train_stereo.py --erase_concept 'Barack Obama' --generic_prompt 'person' --train_method xattn --train_data_dir '../data_root/generated/stereo/a photo of Barack Obama/' --learnable_property person --initializer_token toy --output_dir ../data_root2/logs/suma/suma-x.tie70_U.obama_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 70 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
python train_suma.py --erase_concept 'Barack Obama' --generic_concept 'person'  --output_dir ../data_root2/logs/suma/suma-x.tie70_U.obama_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a photo of Barack Obama/' --learnable_property person  --device $device 
python -W ignore train_stereo.py --erase_concept 'a painting in the style of Picasso' --generic_prompt 'a painting in the style of artist' --train_method xattn --train_data_dir '../data_root/generated/stereo/a painting in the style of Picasso/' --learnable_property style --initializer_token toy --output_dir ../data_root2/logs/suma/suma-x.tie70_U.picasso_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 70 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
python train_suma.py --erase_concept 'a painting in the style of Picasso' --generic_concept 'a painting in the style of artist'  --output_dir ../data_root2/logs/suma/suma-x.tie70_U.picasso_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a painting in the style of Picasso/' --learnable_property style  --device $device 

# # python -W ignore train_stereo.py --erase_concept 'Margot Robbie' --generic_prompt 'person' --train_method xattn --train_data_dir '../data_root/generated/stereo/a photo of Margot Robbie/' --learnable_property person --initializer_token toy --output_dir ../data_root2/logs/suma/suma.tie50_U.mrobbie_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 10 --ti_max_train_steps 10 --num_of_adv_concepts 2 --early_step 5 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
# python train_suma.py --erase_concept 'Margot Robbie' --generic_concept 'person'  --output_dir ../data_root2/logs/suma/suma.tie50_U.mrobbie_sd1.4.bf16_r0 --train_method xattn --suma_step 20 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a photo of Margot Robbie/' --learnable_property person  --device $device 


# python -W ignore train_stereo.py --erase_concept 'Margot Robbie' --generic_prompt 'person' --train_method xattn --train_data_dir '../data_root/generated/stereo/a photo of Margot Robbie/' --learnable_property person --initializer_token toy --output_dir ../data_root2/logs/suma/suma.tie50_U.mrobbie_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 50 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
# python train_suma.py --erase_concept 'Margot Robbie' --generic_concept 'person'  --output_dir ../data_root2/logs/suma/suma.tie50_U.mrobbie_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a photo of Margot Robbie/' --learnable_property person  --device $device 
# python -W ignore train_stereo.py --erase_concept 'David Beckham' --generic_prompt 'person' --train_method xattn --train_data_dir '../data_root/generated/stereo/a photo of David Beckham/' --learnable_property person --initializer_token toy --output_dir ../data_root2/logs/suma/suma.tie50_U.beckham_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 50 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
# python train_suma.py --erase_concept 'David Beckham' --generic_concept 'person'  --output_dir ../data_root2/logs/suma/suma.tie50_U.beckham_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a photo of David Beckham/' --learnable_property person  --device $device 
# python -W ignore train_stereo.py --erase_concept 'Rihanna' --generic_prompt 'person' --train_method xattn --train_data_dir '../data_root/generated/stereo/a photo of Rihanna/' --learnable_property person --initializer_token toy --output_dir ../data_root2/logs/suma/suma.tie50_U.rihanna_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 50 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
# python train_suma.py --erase_concept 'Rihanna' --generic_concept 'person'  --output_dir ../data_root2/logs/suma/suma.tie50_U.rihanna_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a photo of Rihanna/' --learnable_property person  --device $device 
# python -W ignore train_stereo.py --erase_concept 'Barack Obama' --generic_prompt 'person' --train_method xattn --train_data_dir '../data_root/generated/stereo/a photo of Barack Obama/' --learnable_property person --initializer_token toy --output_dir ../data_root2/logs/suma/suma.tie50_U.obama_sd1.4.bf16_r0/stereo --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --n_iterations 3 --iterations 200 --ti_max_train_steps 500 --num_of_adv_concepts 2 --early_step 50 --attack_eval_images data/images/eval/dummy/ --mode stereo --compositional_guidance_scale 2  --anchor_concept_path utils/anchor_prompts.json  --device $device 
# python train_suma.py --erase_concept 'Barack Obama' --generic_concept 'person'  --output_dir ../data_root2/logs/suma/suma.tie50_U.obama_sd1.4.bf16_r0 --train_method xattn --suma_step 3000 --subspace_elimination_lr 5e-06 --train_data_dir '../data_root/generated/stereo/a photo of Barack Obama/' --learnable_property person  --device $device 