export CUDA_VISIBLE_DEVICES=0

python generate_images.py  --prompt "A photo of Amy Adams" --output_dir "../data_root/generated/stereo/A photo of Amy Adams/"  --num_images 500 
python -W ignore train.py --erase_concept 'Amy Adams' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Amy Adams/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Amy Adams" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Amy Adams/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json


# python -W ignore train.py --erase_concept 'Rihanna' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Rihanna/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Rihanna" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Rihanna/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Anne Adam' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Anne Adam/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Anne Adam" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Anne Adam/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json


# python -W ignore train.py --erase_concept 'Barrack Obama' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Barrack Obama/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Barrack Obama" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Barrack Obama/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Anne Hathaway' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Anne Hathaway/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Anne Hathaway" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Anne Hathaway/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json

# python -W ignore train.py --erase_concept 'Ed Sheeran' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Ed Sheeran/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Ed Sheeran" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Ed Sheeran/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Margot Robbie' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Margot Robbie/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Margot Robbie" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Margot Robbie/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Chris Hemsworth' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Chris Hemsworth/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Chris Hemsworth" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Chris Hemsworth/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Chris Evans' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Chris Evans/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Chris Evans" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Chris Evans/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Mariah Carey' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Mariah Carey/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Mariah Carey" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Mariah Carey/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Octavia Spencer' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Octavia Spencer/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Octavia Spencer" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Octavia Spencer/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Morgan Freeman' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Morgan Freeman/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Morgan Freeman" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Morgan Freeman/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Drake' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Drake/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Drake" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Drake/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json

# need generation and anchor prompt (from chatgpt)
# python -W ignore train.py --erase_concept 'Adam Driver' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Adam Driver/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Adam Driver" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Adam Driver/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Andrew Garfield' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Andrew Garfield/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Andrew Garfield" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Andrew Garfield/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Angelina Jolie' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Angelina Jolie/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Angelina Jolie" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Angelina Jolie/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Amber Heard' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Amber Heard/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Amber Heard" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Amber Heard/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Oprah Winfrey' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Oprah Winfrey/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Oprah Winfrey" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Oprah Winfrey/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Idris Elba' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Idris Elba/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Idris Elba" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Idris Elba/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json

# python -W ignore train.py --erase_concept 'Barrack Obama' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Barrack Obama/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Barrack Obama" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Barrack Obama/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Chris Hemsworth' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Chris Hemsworth/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Chris Hemsworth" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Chris Hemsworth/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Chris Evans' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Chris Evans/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Chris Evans" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Chris Evans/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json

# python -W ignore train.py --erase_concept 'Ed Sheeran' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Ed Sheeran/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Ed Sheeran" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Ed Sheeran/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Mariah Carey' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Mariah Carey/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Mariah Carey" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Mariah Carey/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Octavia Spencer' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Octavia Spencer/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Octavia Spencer" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Octavia Spencer/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json 

# python -W ignore train.py --erase_concept 'Margot Robbie' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Margot Robbie/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Margot Robbie" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Margot Robbie/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Morgan Freeman' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Morgan Freeman/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Morgan Freeman" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Morgan Freeman/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Drake' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Drake/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Drake" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Drake/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json


# python -W ignore train.py --erase_concept 'Barrack Obama' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Barrack Obama/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Barrack Obama" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Barrack Obama/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Chris Hemsworth' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Chris Hemsworth/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Chris Hemsworth" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Chris Hemsworth/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Chris Evans' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Chris Evans/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Chris Evans" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Chris Evans/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python generate_images.py --output_dir "../data_root/generated/stereo/A photo of Barrack Obama/" --prompt "A photo of Barrack Obama" --num_images 500
# python -W ignore train.py --erase_concept 'Barrack Obama' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Barrack Obama/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/obama" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Barrack Obama/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json

# python generate_images.py --output_dir ../data_root/generated/stereo/eval/obama/ --prompt "A photo of Barrack Obama" --num_images 500


# python -W ignore train.py --erase_concept 'Barrack Obama' --train_method noxattn --train_data_dir ../data_root/generated/stereo/obama/ --learnable_property 'object' --initializer_token 'person' --output_dir ../data_root/generated/stereo/weights/obama --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images ../data_root/generated/stereo/eval/obama/ --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2  --anchor_concept_path utils/anchor_prompts.json

# attack_eval_images is just for eval