# export CUDA_VISIBLE_DEVICES=0
export device="cuda:0"
python -W ignore train.py --erase_concept 'naked person' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of naked person/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.naked_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of naked person/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
python -W ignore train.py --erase_concept 'a painting in the style of Jackson Pollock' --train_method noxattn --train_data_dir "../data_root/generated/stereo/a painting in the style of Jackson Pollock/" --learnable_property 'style' --initializer_token 'art' --output_dir "../data_root/logs/stereo/stereo_U.pollock_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of a painting in the style of Jackson Pollock/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 

# python -W ignore train.py --erase_concept 'naked person' --train_method noxattn --train_data_dir "../data_root/generated/stereo/a photo of naked person/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.naked_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of naked person/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 

# python -W ignore train.py --erase_concept 'naked person' --train_method noxattn --train_data_dir "../data_root/generated/stereo/a photo of naked person/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.naked_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of naked person/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 



# python generate_images.py  --prompt "A photo of David Beckham" --output_dir "../data_root/generated/stereo/A photo of David Beckham/"  --num_images 500 
# python generate_images.py  --prompt "A photo of Margot Robbie" --output_dir "../data_root/generated/stereo/A photo of Margot Robbie/"  --num_images 500 
# python generate_images.py  --prompt "A photo of Barack Obama" --output_dir "../data_root/generated/stereo/A photo of Barack Obama/"  --num_images 500 
# python generate_images.py  --prompt "A photo of Rihanna" --output_dir "../data_root/generated/stereo/A photo of Rihanna/"  --num_images 500 


# python generate_images.py  --prompt "a painting in the style of Van Gogh" --output_dir "../data_root/generated/stereo/a painting in the style of Van Gogh/"  --num_images 500 
# python generate_images.py  --prompt "a painting in the style of Picasso" --output_dir "../data_root/generated/stereo/a painting in the style of Picasso/"  --num_images 500 
# python generate_images.py  --prompt "a painting in the style of Claude Monet" --output_dir "../data_root/generated/stereo/a painting in the style of Claude Monet/"  --num_images 500 
# python generate_images.py  --prompt "a painting in the style of Jackson Pollock" --output_dir "../data_root/generated/stereo/a painting in the style of Jackson Pollock/"  --num_images 500 




# python -W ignore train.py --erase_concept 'Donald Trump' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Donald Trump/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.dtrump_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Donald Trump/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42
# python -W ignore train.py --erase_concept 'Barack Obama' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Barack Obama/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.obama_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Barack Obama/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42
# python -W ignore train.py --erase_concept 'Margot Robbie' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Margot Robbie/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.mrobbie_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Margot Robbie/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42
# python -W ignore train.py --erase_concept 'mickey mouse' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of mickey mouse/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.mmouse_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of mickey mouse/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42
# python -W ignore train.py --erase_concept 'persian cat' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of persian cat/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.percat_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of persian cat/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42
# python -W ignore train.py --erase_concept 'ganesha' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of ganesha/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.ganesha_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of ganesha/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42
# python -W ignore train.py --erase_concept 'tank' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of tank/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.tank_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of tank/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42
# python -W ignore train.py --erase_concept 'pad thai' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of pad thai/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.padthai_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of pad thai/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42


# python generate_images.py  --prompt "A photo of Donald Trump" --output_dir "../data_root/generated/stereo/A photo of Donald Trump/"  --num_images 500 
# python generate_images.py  --prompt "A photo of Barack Obama" --output_dir "../data_root/generated/stereo/A photo of Barack Obama/"  --num_images 500 


# python -W ignore train.py --erase_concept 'Donald Trump' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Donald Trump/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.U.percat_sd1.4.bf16.bs4_r0.uS1000.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Donald Trump/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42
# python -W ignore train.py --erase_concept 'Barack Obama' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Barack Obama/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.U.percat_sd1.4.bf16.bs4_r0.uS1000.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Barack Obama/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42
# python -W ignore train.py --erase_concept 'Margot Robbie' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Margot Robbie/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.U.percat_sd1.4.bf16.bs4_r0.uS1000.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Margot Robbie/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42
# python -W ignore train.py --erase_concept 'mickey mouse' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of mickey mouse/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.U.percat_sd1.4.bf16.bs4_r0.uS1000.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of mickey mouse/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42
# python -W ignore train.py --erase_concept 'persian cat' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of persian cat/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.U.percat_sd1.4.bf16.bs4_r0.uS1000.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of persian cat/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42
# python -W ignore train.py --erase_concept 'ganesha' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of ganesha/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.U.percat_sd1.4.bf16.bs4_r0.uS1000.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of ganesha/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42
# python -W ignore train.py --erase_concept 'tank' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of tank/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.U.percat_sd1.4.bf16.bs4_r0.uS1000.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of tank/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42
# python -W ignore train.py --erase_concept 'pad thai' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of pad thai/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.U.percat_sd1.4.bf16.bs4_r0.uS1000.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00.nG1.50pG2.00_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of pad thai/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42




# python -W ignore train.py --erase_concept 'Rihanna' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Rihanna/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Rihanna.ACeleb.nG2.00pG4.00" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Rihanna/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json --load_ste '../data_root/logs/stereo/Rihanna/ste_stage_model.pt' --neg_guidance_scale 2.00 --pos_guidance_scale 4.00
# python -W ignore train.py --erase_concept 'Rihanna' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Rihanna/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Rihanna.ACeleb.nG2.00pG3.00" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Rihanna/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json --load_ste '../data_root/logs/stereo/Rihanna/ste_stage_model.pt' --neg_guidance_scale 2.00 --pos_guidance_scale 3.00


# python -W ignore train.py --erase_concept 'Rihanna' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Rihanna/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Rihanna.ACeleb.nG2pG4" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Rihanna/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json --load_ste '../data_root/logs/stereo/Rihanna/ste_stage_model.pt' --neg_guidance_scale 2 --pos_guidance_scale 4

# python -W ignore train.py --erase_concept 'Rihanna' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Rihanna/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Rihanna.ACeleb" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Rihanna/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json --load_ste '../data_root/logs/stereo/Rihanna/ste_stage_model.pt'




# python -W ignore train.py --erase_concept 'Barack Obama' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Barack Obama/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Barack Obama.ACeleb" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Barack Obama/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Rihanna' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Rihanna/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Rihanna.ACeleb" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Rihanna/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Ed Sheeran' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Ed Sheeran/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Ed Sheeran.ACeleb" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Ed Sheeran/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Margot Robbie' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Margot Robbie/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Margot Robbie.ACeleb" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Margot Robbie/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Chris Hemsworth' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Chris Hemsworth/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Chris Hemsworth.ACeleb" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Chris Hemsworth/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Chris Evans' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Chris Evans/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Chris Evans.ACeleb" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Chris Evans/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Amy Adams' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Amy Adams/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Amy Adams.ACeleb" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Amy Adams/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Anne Hathaway' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Anne Hathaway/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Anne Hathaway.ACeleb" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Anne Hathaway/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Mariah Carey' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Mariah Carey/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Mariah Carey.ACeleb" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Mariah Carey/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Octavia Spencer' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Octavia Spencer/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Octavia Spencer.ACeleb" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Octavia Spencer/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Morgan Freeman' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Morgan Freeman/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Morgan Freeman.ACeleb" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Morgan Freeman/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Drake' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Drake/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Drake.ACeleb" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Drake/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json


# python -W ignore train.py --erase_concept 'Barrack Obama' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Barrack Obama/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Barrack Obama" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Barrack Obama/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Rihanna' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Rihanna/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Rihanna" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Rihanna/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Ed Sheeran' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Ed Sheeran/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Ed Sheeran" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Ed Sheeran/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Margot Robbie' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Margot Robbie/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Margot Robbie" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Margot Robbie/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Chris Hemsworth' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Chris Hemsworth/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Chris Hemsworth" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Chris Hemsworth/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Chris Evans' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Chris Evans/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Chris Evans" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Chris Evans/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Amy Adams' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Amy Adams/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Amy Adams" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Amy Adams/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Anne Hathaway' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Anne Hathaway/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Anne Hathaway" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Anne Hathaway/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Mariah Carey' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Mariah Carey/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Mariah Carey" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Mariah Carey/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Octavia Spencer' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Octavia Spencer/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Octavia Spencer" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Octavia Spencer/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Morgan Freeman' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Morgan Freeman/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Morgan Freeman" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Morgan Freeman/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Drake' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Drake/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Drake" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Drake/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python generate_images.py  --prompt "A photo of Amy Adams" --output_dir "../data_root/generated/stereo/A photo of Amy Adams/"  --num_images 500 
# python -W ignore train.py --erase_concept 'Amy Adams' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Amy Adams/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Amy Adams" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Amy Adams/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json


# python -W ignore train.py --erase_concept 'Rihanna' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Rihanna/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Rihanna" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Rihanna/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Anne Adam' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Anne Adam/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Anne Adam" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Anne Adam/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json


# python -W ignore train.py --erase_concept 'Barrack Obama' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Barrack Obama/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Barrack Obama" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Barrack Obama/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Anne Hathaway' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Anne Hathaway/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Anne Hathaway" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Anne Hathaway/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json

# python -W ignore train.py --erase_concept 'Ed Sheeran' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Ed Sheeran/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Ed Sheeran" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Ed Sheeran/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Margot Robbie' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Margot Robbie/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Margot Robbie" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Margot Robbie/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Chris Hemsworth' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Chris Hemsworth/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Chris Hemsworth" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Chris Hemsworth/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Chris Evans' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Chris Evans/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Chris Evans" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Chris Evans/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Mariah Carey' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Mariah Carey/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Mariah Carey" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Mariah Carey/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Octavia Spencer' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Octavia Spencer/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Octavia Spencer" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Octavia Spencer/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Morgan Freeman' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Morgan Freeman/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Morgan Freeman" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Morgan Freeman/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Drake' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Drake/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Drake" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Drake/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json

# need generation and anchor prompt (from chatgpt)
# python -W ignore train.py --erase_concept 'Adam Driver' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Adam Driver/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Adam Driver" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Adam Driver/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Andrew Garfield' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Andrew Garfield/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Andrew Garfield" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Andrew Garfield/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Angelina Jolie' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Angelina Jolie/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Angelina Jolie" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Angelina Jolie/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Amber Heard' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Amber Heard/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Amber Heard" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Amber Heard/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Oprah Winfrey' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Oprah Winfrey/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Oprah Winfrey" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Oprah Winfrey/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Idris Elba' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Idris Elba/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Idris Elba" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Idris Elba/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json

# python -W ignore train.py --erase_concept 'Barrack Obama' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Barrack Obama/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Barrack Obama" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Barrack Obama/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Chris Hemsworth' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Chris Hemsworth/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Chris Hemsworth" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Chris Hemsworth/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Chris Evans' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Chris Evans/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Chris Evans" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Chris Evans/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json

# python -W ignore train.py --erase_concept 'Ed Sheeran' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Ed Sheeran/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Ed Sheeran" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Ed Sheeran/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Mariah Carey' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Mariah Carey/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Mariah Carey" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Mariah Carey/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Octavia Spencer' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Octavia Spencer/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Octavia Spencer" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Octavia Spencer/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json 

# python -W ignore train.py --erase_concept 'Margot Robbie' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Margot Robbie/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Margot Robbie" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Margot Robbie/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Morgan Freeman' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Morgan Freeman/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Morgan Freeman" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Morgan Freeman/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Drake' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Drake/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Drake" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Drake/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json


# python -W ignore train.py --erase_concept 'Barrack Obama' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Barrack Obama/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Barrack Obama" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Barrack Obama/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Chris Hemsworth' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Chris Hemsworth/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Chris Hemsworth" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Chris Hemsworth/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Chris Evans' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Chris Evans/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Chris Evans" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Chris Evans/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python generate_images.py --output_dir "../data_root/generated/stereo/A photo of Barrack Obama/" --prompt "A photo of Barrack Obama" --num_images 500
# python -W ignore train.py --erase_concept 'Barrack Obama' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Barrack Obama/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/obama" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Barrack Obama/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json

# python generate_images.py --output_dir ../data_root/generated/stereo/eval/obama/ --prompt "A photo of Barrack Obama" --num_images 500


# python -W ignore train.py --erase_concept 'Barrack Obama' --train_method noxattn --train_data_dir ../data_root/generated/stereo/obama/ --learnable_property 'object' --initializer_token 'person' --output_dir ../data_root/generated/stereo/weights/obama --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images ../data_root/generated/stereo/eval/obama/ --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2  --anchor_concept_path utils/anchor_prompts.json

# attack_eval_images is just for eval