export CUDA_VISIBLE_DEVICES=2

python -W ignore train.py --erase_concept 'Rihanna' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Rihanna/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Rihanna.ACeleb.nG2.00pG8.00" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Rihanna/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json --load_ste '../data_root/logs/stereo/Rihanna/ste_stage_model.pt' --neg_guidance_scale 2.00 --pos_guidance_scale 8.00
python -W ignore train.py --erase_concept 'Rihanna' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Rihanna/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Rihanna.ACeleb.nG1.10pG2.00" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Rihanna/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json --load_ste '../data_root/logs/stereo/Rihanna/ste_stage_model.pt' --neg_guidance_scale 1.10 --pos_guidance_scale 2.00


# python -W ignore train.py --erase_concept 'Rihanna' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Rihanna/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Rihanna.ACeleb.nG1.25pG2" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Rihanna/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json --load_ste '../data_root/logs/stereo/Rihanna/ste_stage_model.pt' --neg_guidance_scale 1.25 --pos_guidance_scale 2


# python -W ignore train.py --erase_concept 'Chris Hemsworth' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Chris Hemsworth/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Chris Hemsworth.ACeleb" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Chris Hemsworth/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Chris Evans' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Chris Evans/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Chris Evans.ACeleb" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Chris Evans/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Amy Adams' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Amy Adams/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Amy Adams.ACeleb" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Amy Adams/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Anne Hathaway' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Anne Hathaway/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Anne Hathaway.ACeleb" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Anne Hathaway/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Mariah Carey' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Mariah Carey/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Mariah Carey.ACeleb" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Mariah Carey/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Octavia Spencer' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Octavia Spencer/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Octavia Spencer.ACeleb" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Octavia Spencer/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Morgan Freeman' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Morgan Freeman/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Morgan Freeman.ACeleb" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Morgan Freeman/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Drake' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Drake/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Drake.ACeleb" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Drake/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json

# python -W ignore train.py --erase_concept 'Chris Hemsworth' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Chris Hemsworth/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Chris Hemsworth" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Chris Hemsworth/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Chris Evans' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Chris Evans/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Chris Evans" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Chris Evans/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Amy Adams' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Amy Adams/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Amy Adams" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Amy Adams/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Anne Hathaway' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Anne Hathaway/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Anne Hathaway" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Anne Hathaway/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Mariah Carey' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Mariah Carey/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Mariah Carey" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Mariah Carey/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Octavia Spencer' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Octavia Spencer/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Octavia Spencer" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Octavia Spencer/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Morgan Freeman' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Morgan Freeman/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Morgan Freeman" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Morgan Freeman/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Drake' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Drake/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Drake" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Drake/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/person_anchor_prompts.json