export CUDA_VISIBLE_DEVICES=3
export device="cuda:0"

# python -W ignore train.py --erase_concept 'David Beckham' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of David Beckham/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.beckham_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of David Beckham/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
# python -W ignore train.py --erase_concept 'Margot Robbie' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Margot Robbie/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.mrobbie_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Margot Robbie/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
# python -W ignore train.py --erase_concept 'Barack Obama' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Barack Obama/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.obama_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Barack Obama/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
# python -W ignore train.py --erase_concept 'Rihanna' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Rihanna/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.rihanna_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Rihanna/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 


python -W ignore train.py --erase_concept 'a painting in the style of Van Gogh' --train_method noxattn --train_data_dir "../data_root/generated/stereo/a painting in the style of Van Gogh/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.vgogh_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of a painting in the style of Van Gogh/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
python -W ignore train.py --erase_concept 'a painting in the style of Picasso' --train_method noxattn --train_data_dir "../data_root/generated/stereo/a painting in the style of Picasso/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.picasso_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of a painting in the style of Picasso/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
python -W ignore train.py --erase_concept 'a painting in the style of Claude Monet' --train_method noxattn --train_data_dir "../data_root/generated/stereo/a painting in the style of Claude Monet/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.cmonet_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of a painting in the style of Claude Monet/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device 
python -W ignore train.py --erase_concept 'a painting in the style of Jackson Pollock' --train_method noxattn --train_data_dir "../data_root/generated/stereo/a painting in the style of Jackson Pollock/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/stereo_U.pollock_sd1.4.bf16_r0" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of a painting in the style of Jackson Pollock/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/anchor_prompts_custom.json --seed 42 --device $device
# python generate_images.py  --prompt "A photo of tank" --output_dir "../data_root/generated/stereo/A photo of tank/"  --num_images 500 
# python generate_images.py  --prompt "A photo of pad thai" --output_dir "../data_root/generated/stereo/A photo of pad thai/"  --num_images 500 



# python -W ignore train.py --erase_concept 'Rihanna' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Rihanna/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Rihanna.ACeleb.nG1.25pG2.00" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Rihanna/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json --load_ste '../data_root/logs/stereo/Rihanna/ste_stage_model.pt' --neg_guidance_scale 1.25 --pos_guidance_scale 2.00
# python -W ignore train.py --erase_concept 'Rihanna' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Rihanna/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Rihanna.ACeleb.nG1.50pG2.00" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Rihanna/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json --load_ste '../data_root/logs/stereo/Rihanna/ste_stage_model.pt' --neg_guidance_scale 1.50 --pos_guidance_scale 2.00


# python -W ignore train.py --erase_concept 'Rihanna' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Rihanna/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Rihanna.ACeleb.nG2pG8" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Rihanna/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json --load_ste '../data_root/logs/stereo/Rihanna/ste_stage_model.pt' --neg_guidance_scale 2 --pos_guidance_scale 8



# python -W ignore train.py --erase_concept 'Mariah Carey' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Mariah Carey/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Mariah Carey.ACeleb" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Mariah Carey/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Octavia Spencer' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Octavia Spencer/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Octavia Spencer.ACeleb" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Octavia Spencer/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Morgan Freeman' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Morgan Freeman/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Morgan Freeman.ACeleb" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Morgan Freeman/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json
# python -W ignore train.py --erase_concept 'Drake' --train_method noxattn --train_data_dir "../data_root/generated/stereo/A photo of Drake/" --learnable_property 'object' --initializer_token 'person' --output_dir "../data_root/logs/stereo/Drake.ACeleb" --mode stereo --unet_ckpt_to_attack final_reo_unet.pt --attack_eval_images  "../data_root/generated/stereo/A photo of Drake/" --compositional_guidance_scale 2 --n_iterations 2 --num_of_adv_concepts 2   --anchor_concept_path utils/celebname_anchor_prompts.json
